apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend-app
data:
  MY_DATABASE_DRIVER: "postgres"
  DB_HOST: "postgres-service"
  DB_USER_NAME: "postgres"
  DB_NAME: "backenddb"
  DB_PORT: "5432"
